[server]
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
allowRunOnSave = false
runOnSave = false
fileWatcherType = "none"
fastReruns = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8080

[client]
toolbarMode = "minimal"
showErrorDetails = false