[server]
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
allowRunOnSave = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"